// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBt8IGXh3kGdPTnP4Y7Cqct5j6eQ98DtU',
    appId: '1:487656917571:web:b02a72ed58ba1be69422f6',
    messagingSenderId: '487656917571',
    projectId: 'immoplace-de022',
    authDomain: 'immoplace-de022.firebaseapp.com',
    storageBucket: 'immoplace-de022.appspot.com',
    measurementId: 'G-SSE4SVW8QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_Mi4SKQel06xGscvRMPi1EyFpdsH3IE',
    appId: '1:487656917571:android:0026c6c192c867689422f6',
    messagingSenderId: '487656917571',
    projectId: 'immoplace-de022',
    storageBucket: 'immoplace-de022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1faYD--tsSnFebYuuM68sioEI6nV-u6o',
    appId: '1:487656917571:ios:59b77d2548cb87b79422f6',
    messagingSenderId: '487656917571',
    projectId: 'immoplace-de022',
    storageBucket: 'immoplace-de022.appspot.com',
    iosClientId: '487656917571-i1i355qmcc6afikoshlj8uigh7rb5hf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.immolinkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1faYD--tsSnFebYuuM68sioEI6nV-u6o',
    appId: '1:487656917571:ios:59b77d2548cb87b79422f6',
    messagingSenderId: '487656917571',
    projectId: 'immoplace-de022',
    storageBucket: 'immoplace-de022.appspot.com',
    iosClientId: '487656917571-i1i355qmcc6afikoshlj8uigh7rb5hf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.immolinkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBt8IGXh3kGdPTnP4Y7Cqct5j6eQ98DtU',
    appId: '1:487656917571:web:61419db652be05439422f6',
    messagingSenderId: '487656917571',
    projectId: 'immoplace-de022',
    authDomain: 'immoplace-de022.firebaseapp.com',
    storageBucket: 'immoplace-de022.appspot.com',
    measurementId: 'G-MCBSSYEDWL',
  );

}